bool hold  # true to mask the body part
bool place # true if direction notation is 'place'
float64 direction
float64 level

# direction radians reference
float64 FORWARD = 0.0
float64 LEFT_FORWARD = 0.785398
float64 LEFT = 1.570796
float64 LEFT_BACK = 2.356194
float64 BACK = 3.141592
float64 RIGHT_FORWARD = -0.785398
float64 RIGHT = -1.570796
float64 RIGHT_BACK = -2.356194

# level value reference
float64 HIGH = 1.0
float64 MIDDLE = 0.0
float64 LOW = -1.0

